"""add studies soft delete

Revision ID: 1c46bd1eb5d3
Revises: bd11f85fca75
Create Date: 2026-09-11 17:12:42.329995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c46bd1eb5d3"
down_revision: str | None = "bd11f85fca75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("studies", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studies", "deleted_at")
    # ### end Alembic commands ###
